sonar.projectKey=qrscan
sonar.projectName=QRScan
sonar.projectVersion=0.1.0
sonar.sources=ui,src-tauri/src
sonar.exclusions=ui/lib/**/*,src-tauri/target/**/*,src-tauri/gen/**/*,.package/**/*,.github/**/*,dist/**/*
sonar.sourceEncoding=UTF-8
sonar.externalIssuesReportPaths=/opt/artifacts/semgrep-sonar.json
